sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo apt install libboost-all-dev
  - sudo apt install libjpeg-turbo8-dev
  - sudo apt install libpng++-dev
  - sudo apt install libtiff5-dev
  - sudo apt install cmake
language: cpp
compiler:
  - gcc-5
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
