macro(COMPILE)
if (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  add_definitions("/W2")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set (CMAKE_CXX_STANDARD 14)
  add_definitions("-Wall")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set (CMAKE_CXX_STANDARD 14)
    add_definitions("-Wall -fcolor-diagnostics")
endif()
endmacro()
